name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      
      - name: Run vet
        run: go vet ./...
      
      - name: Run fmt check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Please run 'make fmt' to format your code"
            gofmt -s -d .
            exit 1
          fi

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install dependencies
        run: |
          go mod download
          go mod verify

      - name: Run unit tests only (exclude integration)
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic \
            $(go list ./... | grep -v /test/integration)

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
          flags: unittests

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
      
      - name: Install buf
        run: |
          BUF_VERSION="1.32.0"
          curl -sSL "https://github.com/bufbuild/buf/releases/download/v${BUF_VERSION}/buf-Linux-x86_64" -o /tmp/buf
          chmod +x /tmp/buf
          sudo mv /tmp/buf /usr/local/bin/buf
          buf --version
      
      - name: Build binary
        run: make build
      
      - name: Start Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up -d
          sleep 15  # Wait for Kafka to be ready
      
      - name: Run integration tests
        run: cd test/integration && go test -v -timeout 5m
      
      - name: Stop Docker Compose
        if: always()
        run: docker compose -f docker-compose.test.yml down -v

  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    needs: [test, integration-test]
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          output_name="buf-kcat-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            output_name="${output_name}.exe"
          fi
          go build -v -o ${output_name} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: buf-kcat-${{ matrix.goos }}-${{ matrix.goarch }}
          path: buf-kcat-${{ matrix.goos }}-${{ matrix.goarch }}*

  # Summary job to ensure all checks pass
  ci-success:
    name: CI Success
    if: always()
    runs-on: ubuntu-latest
    needs: [lint, test, integration-test, build]
    steps:
      - name: Check if all jobs succeeded
        run: |
          if [[ "${{ needs.lint.result }}" != "success" || \
                "${{ needs.test.result }}" != "success" || \
                "${{ needs.integration-test.result }}" != "success" || \
                "${{ needs.build.result }}" != "success" ]]; then
            echo "One or more CI jobs failed"
            exit 1
          fi
          echo "All CI jobs passed successfully!"